name = "CosmoRegistry"
uuid = "b5a69fe8-1b48-400f-b5e7-a6cbc06d7432"
repo = "https://github.com/gaetanfacchinetti/CosmoRegistry.git"

[packages]
fab82211-602b-461d-8fab-2b676713216d = { name = "CosmoTools", path = "C/CosmoTools" }
